/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  classicsSidebar: [{type: 'autogenerated', dirName: '經'}],
  historySidebar: [{type: 'autogenerated', dirName: '史'}],
  childSidebar: [{type: 'autogenerated', dirName: '子'}],
  collectedworksSidebar: [{type: 'autogenerated', dirName: '集'}],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
